Feature1
Teaching-projects/SOE-SZTA-2021-Sasok pull request #3
Opened 2021-02-22 22:00 UTC by phollaki

Készen áll a feature1 branch a mergelésre!

2021-02-26 10:56 UTC, hegyhati requested changes

2021-02-26 10:56 UTC, hegyhati commented on Main.java
> +            if(our.isAlive() && enemy.isAlive()){
Itt a sajatunk tesztelese kisse overkill.

2021-02-26 10:56 UTC, hegyhati commented on Main.java
> +        System.out.println("Warrior élete és sebzése: "+ warrior.hp +", "+ warrior.dmg + " || Shaman élete és sebzése: " + shaman.hp + ", " + shaman.dmg + '\n');
az nem szep, hogy ezek public- ban elerhetok.

2021-02-26 10:56 UTC, hegyhati commented on Main.java
> +                    System.out.println(i + ". körben a maradék életünk: " + our.hp + ", lenne az ellenség maradék élete: " + enemy.hp + " lenne");
Egy kicsit logikusabb lenne, ha a Unit-nak lenne neve, es itt nem mi/ellenseg lenne, hanem konkretan az, hogy ki kit ut.

2021-02-26 10:56 UTC, hegyhati commented on Main.java
> +                    System.out.println(i + ". körben a maradék életünk: " + our.hp + ", lenne az ellenség maradék élete: " + enemy.hp + " lenne");
Illetve ezt az if-et nem teljesen ertem. a vegen a "lenne" szo miatt van? Illetve igy csak egy utes-visszautes utan irja ki, nem minden utes utan.

2021-02-26 10:56 UTC, hegyhati commented on Main.java
> +        System.out.println((our.hp>enemy.hp) ? "\nNyertünk!" : "\nVesztettünk!");
ez egy implicit teszt. Nem az nyert akinek tobb a hp-je, hanem az, aki eletben maradt. Az, hogy annak tobb a hp-je, az persze egy kovetkezmeny. De az if-et arra irjuk, amire akarjuk, ne annak egy kovetkezmenyere.

2021-03-02 11:02 UTC, phollaki commented
@hegyhati

2021-03-02 13:59 UTC, hegyhati requested changes
Az a private-ozas azert illene, az initialize sem a legjobb nevvalasztas, de az elfer.

2021-03-02 13:59 UTC, hegyhati commented on Main.java
> +        System.out.println("A Csata elkezdődött! " + unit1.name + " kezdheti a támadást " + unit2.name + (" ellen."));
A  nev meg mindig public adattag, de ennyi elfer.

2021-03-02 13:59 UTC, hegyhati commented on Main.java
> +        battle(unit1, unit2);
a fuggveny nevvalasztasa innentol kezdve annyira nem szerenses, mert ez nem csak inicializal, hanem mar a csatat is levezenyli.

2021-03-02 13:59 UTC, hegyhati commented on Unit.java
>      int hp;
En azert orulnek a private-nek.

2021-03-02 13:59 UTC, hegyhati commented on Unit.java
>      int hp;
Igazabol ha van egy `final`-unk, ami immutable/primitiv dologra mutat, akkor rendben van ez, Tehat pl a name eseteben.  De pl a hp ele indenkeppen kellene a private.Valoszinuleg szebb lenne ha a dmg elott is lenne, a nev-nel meg izles kerdese, de ha nem private, akkor mondjuk nem art, ha final.

2021-03-08 10:06 UTC, phollaki commented
@hegyhati, légyszi ellenőrizd a megoldásunkat.

2021-03-09 01:36 UTC, hegyhati approved these changes

2021-03-09 01:36 UTC, merged