IO tesztek
Teaching-projects/SOE-SZTA-2021-Sasok pull request #5
Opened 2021-03-10 10:11 UTC by nemethdav

@hegyhati légyszíves nézz rá, hogy jók lesznek-e így az IO tesztek

2021-03-10 12:08 UTC, hegyhati requested changes
Rendben van alapvetoen, de a teszteke nagyon "egyhanguak". Ilyenkor azert jo volna ramenni edge case-ekre. 

Megnezni, mi van akkor,, ha nagyon nagyok a szamok. Vagy epp hogy pl 0 a tamadasa valamelyiknek. Mi van, ha mindkettonek 0?  Ilyenekre erdemes feldobni 1-1 test case-t es eldonteni, hogy mi a vart kimenet. Szoval meg 1-2 ilyet dobjatok hozza, de amugy jo lesz.

2021-03-11 13:28 UTC, nemethdav commented
@hegyhati légyszíves nézd meg jók-e így a tesztek, valamint javítottam a Main.java-n is, hogy a megfelelő kimenetet kapjuk 0 és valamilyen betű(k) bevitelének esetén is.

2021-03-12 11:28 UTC, hegyhati approved these changes

2021-03-12 11:28 UTC, hegyhati commented on tests/test11.txt.out
> +Nem érvényes értéket adott meg, adjon meg egy számot!
Kerdes, hogy mennyire jo, hogy ez a fura dolog az expected output :-) De most elmegy.

2021-03-12 11:28 UTC, merged