Json
Teaching-projects/SOE-SZTA-2021-Sasok pull request #6
Opened 2021-03-25 11:02 UTC by nemethdav

@hegyhati légyszíves nézd meg készen áll-e a mergelésre.

2021-03-27 11:05 UTC, hegyhati requested changes
Kis szepites struktura teren.

2021-03-27 11:05 UTC, hegyhati commented on Main.java
> +        boolean exists2 = tempFile.exists();
talan erdemes volna azert ezeket nem beegetni, hanem mondjuk args-bol szedni :-)

2021-03-27 11:05 UTC, hegyhati commented on Main.java
> +        Unit unit2;
Az igazan jo az volna, hogyha ezeknek lenne egy olyan konstruktora, ami fajlbol inicializalja magat.

2021-03-27 11:05 UTC, hegyhati commented on Main.java
> +            }
PL itt most minden logika duplikalva van. Ha ezt 1x megirnad, es beletenned egy konstruktorba, akkor itt csak ketszer meghivnad azt a konstruktort es kesz.

2021-03-30 11:27 UTC, nemetha17 commented
@hegyhati Javítva lettek a hibák.

2021-03-31 10:56 UTC, hegyhati submitted a review, later dismissed

2021-03-31 10:56 UTC, hegyhati commented
Reszemrol ok, de a CI tesztek legyenek kipofozva.

2021-04-05 17:45 UTC, nemethdav commented
@hegyhati Máté rá tudnál nézni, hogy miért írja a teszt mindig azt, hogy "does not exist"? Pedig úgy csatoltam a linket a lib mappába ahogy az órán is csináltad, illetve gépen a git bash terminálba simán lefut ezekkel a kódokkal. Köszönöm!

2021-04-06 00:06 UTC, hegyhati commented
![image](https://user-images.githubusercontent.com/13832329/113640829-9ed80380-967c-11eb-9217-bb6fa8d5afa1.png)

2021-04-06 09:11 UTC, nemethdav commented
@hegyhati köszönöm a segítséget! Légyszíves nézd meg, hogy jó-e a mergelésre. Köszönöm.

2021-04-08 08:44 UTC, nemethdav commented
@hegyhati Máté légyszívess nézz rá, és ha jó akkor mergeld össze. Köszönjük!

2021-04-08 13:07 UTC, hegyhati requested changes
Azert ne az legyen a vegleges, hogy "megtamádta". 

A masik, hogy ugye fura fajlneved lett, amit ket modon lehetett megoldanod:
1) azt a csunya fajlnevet hasznalod utana a -cp utan
2) megoldod hogy ne legyen csunya a fajlnev

Ertem en, hogy az 1) az "kevesebb munkas" megoldas, de na, a 2) se lenne tobb, sot, es meg olvashatobb is lenne minden. (ajanlom figyelmedbe a wget parancssori kapcsoloit, kulonosen a `-o`-t :-)

2021-04-08 13:46 UTC, hegyhati commented on .github/workflows/buildTest.yml
> +          mv remotecontent?filepath=org%2Fjson%2Fjson%2F20210307%2Fjson-20210307.jar json.jar
A -o kapcsolo miert nem tetszett? :-)

2021-04-08 13:48 UTC, nemethdav commented on .github/workflows/buildTest.yml
> +          mv remotecontent?filepath=org%2Fjson%2Fjson%2F20210307%2Fjson-20210307.jar json.jar
Mert ezt tudtam fejből azt meg meg kellettem volna keresni, hogy pontosan hogyan kell használnom :D

2021-04-08 14:02 UTC, nemethdav commented
@hegyhati Máté megcsináltam -O kapcsolóval is 😁😃

2021-04-08 14:41 UTC, hegyhati commented on .github/workflows/buildTest.yml
> +          mv remotecontent?filepath=org%2Fjson%2Fjson%2F20210307%2Fjson-20210307.jar json.jar
Hat azert ha en vettem a faradtsagot, hogy lecsekkoljam, hogy valoban az intuitiv -o lesz-e a jo, akkor ugyan mar :-P De latom, kozben kesz :-)

2021-04-08 14:42 UTC, hegyhati approved these changes

2021-04-08 14:42 UTC, hegyhati commented on .github/workflows/buildTest.yml
> +          wget -O json.jar https://search.maven.org/remotecontent?filepath=org/json/json/20210307/json-20210307.jar
nem tudtam, hogy nagy O-val is jo, azt hittem, csak kicsivel. ma is tanultam valamit.

2021-04-08 14:42 UTC, merged