Gui
Teaching-projects/SOE-SZTA-2021-Sasok pull request #7
Opened 2021-04-11 14:50 UTC by nemethdav

@hegyhati Máté nézz rá légyszíves jó lesz-e így. Köszönöm.

2021-04-13 14:27 UTC, hegyhati approved these changes, later dismissed
Lehetne csinositani, de majd a sprintben.

2021-04-13 14:31 UTC, hegyhati commented
A teszteket tegyetek rendbe, aztan bemehet reszemrol.

2021-04-13 14:32 UTC, hegyhati commented
Illetve a CI workflowt-t, hogy ne hasaljon el. Ahogy ma mondtam, unit testek maradjanak, es fussanak, de a az in/out tesztek nem kellenek mar.

2021-04-13 19:35 UTC, nemethdav commented
@hegyhati töröltem az IO teszteket.

2021-04-14 09:41 UTC, hegyhati requested changes
Nana,  CI workflow-t ne tessek kitorolni.

2021-04-14 15:24 UTC, nemethdav commented
@hegyhati Máté javítottam. Ennyi elég a teszt részbe?

2021-04-16 12:56 UTC, hegyhati approved these changes

2021-04-16 12:56 UTC, hegyhati commented
Am legyen.

2021-04-20 07:21 UTC, merged