Junit
Teaching-projects/SOE-SZTA-2021-Sasok pull request #8
Opened 2021-04-11 22:26 UTC by phollaki

@hegyhati Légy szíves ellenőrizd le a munkámat.

2021-04-13 15:12 UTC, hegyhati requested changes
Tessek jobban megtesztelni azt az osztalyt :-)

2021-04-13 15:12 UTC, hegyhati commented on .github/workflows/buildTest.yml
> +          cd ..
Ha mar ketszer megcsinalod, akkor mar erdemes elgondolkodni, hogy hogyan lehetne megoldani, hogy csak egyszer kelljen :-)

2021-04-13 15:12 UTC, hegyhati commented on .github/workflows/buildTest.yml
> +      - run: javac -cp "lib/*" *.java
itt most akkor belefordul a unit teszt is? ha igen, minek?

2021-04-13 15:12 UTC, hegyhati commented on .github/workflows/buildTest.yml
> +          cd ..
(csak otleteles, nem musz have)

2021-04-13 15:12 UTC, hegyhati commented on JunitTest.java
> +public class JunitTest {
Osztalyonkent legyen kulon teszt, ne egy "JunitTest". Szoval ha ez a Unit-ot teszteli, akkor ez UnitTest legyen.

2021-04-13 15:12 UTC, hegyhati commented on .github/workflows/buildTest.yml
> +      - run: java -jar lib/junit.jar -cp "." -c JunitTest --reports-dir="reports/"
Celszeru ezt ugy megirni, hogy ha lesz tobb unit teszt tobb osztalyra, akkor ne kelljen itt hozzanyulni.

2021-04-13 15:12 UTC, hegyhati commented on JunitTest.java
> +        Assertions.assertEquals(unit1.getHp() > 0, true, "hp can not be 0");
`assertTrue` ?

2021-04-13 15:12 UTC, hegyhati commented on JunitTest.java
> +        Assertions.assertEquals(unit1.getHp() > 0, true, "hp can not be 0");
Illetve az uzenet nem teljesen ok, mert a hp igenis lehet 0, csak nem ebben az esetben. Ez igazabol benne van a fentiben.

2021-04-13 15:12 UTC, hegyhati commented on JunitTest.java
> +        Assertions.assertEquals(unit1.getAs() >= 0, true, "as can not be smaller than 0");
ez is igazabol a legelsoben is le van tesztelve, de vegulis maradhatnak.

2021-04-13 15:12 UTC, hegyhati commented on JunitTest.java
> +        Assertions.assertEquals(unit1.getAs() >= 0, true, "as can not be smaller than 0");
de ne, mert nem csak >=0 kell legyen, hanem konkretan 100, szoval ez a teszt akkor is atmenne, ha az a fuggveny 80-at adna vissza, ami nyilvan nem jo. szoval ezeknek nincs ertelme.

2021-04-13 15:12 UTC, hegyhati commented on JunitTest.java
> +        Assertions.assertEquals(unit1.getAs() >= 0, true, "as can not be smaller than 0");
Marmint ugyanannyi erobol lehet irni erosebb tesztet.

2021-04-13 15:12 UTC, hegyhati commented on JunitTest.java
> +        Assertions.assertEquals(unit1.getDMG() > 0 && unit2.getDMG() > 0, true,
na jo, ennek mar tenyleg nem sok ertelme van. Azt tessek letesztelni, hogy az egyik meguti a masikat, akkor annyi lesz-e hp, amennyinek kell lennie. itt lenyegeben 4x ugyanazt a konstruktort meg a 3 gettert tesztelted.

2021-04-13 15:23 UTC, hegyhati commented
och, es most neztem, hogy felcserelted az argumentum sorrendet. `assertArrayEquals(boolean[] expecteds, boolean[] actuals)`

2021-04-14 16:41 UTC, phollaki commented
Amit nem sikerült megcsinálnom:
1.Wget egy sorba, egyidőbe húzza le. Próbáltam wget -O url1 & wget -O url2, de nem sikerült.
2.A workflow IO-tesztes részéhez azért húztam be wgettel a junitot mert különben errorokat hoz, hogy nem ismeri fel a junitos osztályokban lévő parancsokat.

Megpróbáltam több és fontosabb tesztet írni mint előzőleg.
@hegyhati

2021-04-16 13:21 UTC, hegyhati requested changes
Par komment, a sorrendre mindenhol figyelj az assertequalnel.

2021-04-16 13:21 UTC, hegyhati commented on .github/workflows/buildTest.yml
> +      - run: javac -cp "lib/*" *.java
@phollaki ez a kerdes meg all

2021-04-16 13:21 UTC, hegyhati commented on MainTest.java
> +        Assertions.assertTrue(unit1.getHp() > unit2.getHp(), "Harcos should won the battle");
win. de nemertem, miert nem konkret ertekeket tesztelsz.

2021-04-16 13:21 UTC, hegyhati commented on UnitTest.java
> +    }
ezt tovabbra sem ertem. itt miert nem a konkret hp-t kerdezed le. Illetve a battle-t teszteled parameteres tesztekkel, ahol ez nehezen atlathato. Ugyanez volt a masik csapatnal is, gondolom nem veletlen. De ponthogy itt lenne ertelme parameteres tesznek, mert itt tok egyertelmu. Ott egyet sem trivialis kod alapjan latni, hogy mire fog jutni egy battle, hat meg ha 10-et kell parhuzamosan. itt iszont tok egyertelmu, hogy amit megadsz a hp-nak, azt kell visszakapnod.

2021-04-16 13:21 UTC, hegyhati commented on UnitTest.java
> +        Assertions.assertTrue(unit1.getHp() == 100 - unit2.getDMG(), "Attack function is wrong");
vagy a getDMG

2021-04-16 13:21 UTC, hegyhati commented on UnitTest.java
> +        Assertions.assertTrue(unit1.getHp() == 100 - unit2.getDMG(), "Attack function is wrong");
ezert picit talan jobb a lenti teszt.

2021-04-16 13:21 UTC, hegyhati commented on UnitTest.java
> +        Assertions.assertEquals(unit1.getHp(), 20, "Attack function is wrong");
sorrendre figyelj.

2021-04-16 13:23 UTC, hegyhati commented
A wgetnel nem is akartam azt, hogy ket dolgot egy paranccsal szedjel le, nem tudom, ezt mire gondoltad, lehet felrefogalmaztam valahol. 
A bajom a CI-ban az volt, hogy amikor csak buildeled a projektet, akkor a teszteket is lebuildeled, de minek.

2021-04-20 08:42 UTC, phollaki commented
@hegyhati kijavítottam a hibáimat, most már io teszt is megszabadult a junittól.

2021-04-22 16:47 UTC, hegyhati approved these changes, later dismissed
Menjen most mar be, de az a szepseghiba tovabbra is fennall, amit irtam. De ha a standard strukturara szetszeditek a gradle/maven miatt, akkor ez megoldodik.

2021-04-22 16:47 UTC, hegyhati commented on .github/workflows/buildTest.yml
> +      - run: javac -cp "lib/json.jar" *.java
Tovabbra is ott van, hogy leforditod az osszes java fajlodat, igy a tesztjeidet is.

2021-04-25 17:52 UTC, phollaki commented
@hegyhati Bocsi Máté, rácommitoltam a merge engedélyedre, emiatt most újra rá kell pillantanod.

2021-04-25 22:42 UTC, hegyhati approved these changes, later dismissed
Nem ertem, miert szedted ki a sima buildelest, es miert nincs kulon build meg test step, de majd a gradle-lel ez ugyis rendbe lesz rakva.

2021-05-02 14:22 UTC, phollaki commented
@hegyhati Máté lenne egy kérdésem. A merge conflict resolve-ok után is csak engedéllyel megy, ahogy látom. Ilyenkor újra kell engedélyezned ezt is?

2021-05-02 22:48 UTC, hegyhati reviewed
@phollaki igen, kell az uj approve. De 23 tesztetek elszall.

2021-05-03 11:49 UTC, nemethdav approved these changes

2021-05-03 11:49 UTC, merged