Lvlup
Teaching-projects/SOE-SZTA-2021-Sasok pull request #9
Opened 2021-04-14 11:13 UTC by nemetha17

@hegyhati Légy szíves ellenőrizd le, hogy jó-e így a lvlup

2021-04-16 12:30 UTC, hegyhati requested changes

2021-04-16 12:30 UTC, hegyhati commented on Player.java
> +    private float cooldown_multiplier_per_level;
final?

2021-04-16 12:30 UTC, hegyhati commented on Player.java
> +        this.xp = this.xp+super.getDMG();
itt felesleges a super.

2021-04-16 12:30 UTC, hegyhati commented on Player.java
> +            this.xp=0;
hat azert ha 10 xp-ert lepek szintet es lesz 25 XP-m hirtelen, akkor ez a szamolas nem fog tetszeni nekem.

2021-04-16 12:30 UTC, hegyhati commented on Player.java
> +            super.setAs(super.getAs()*cooldown_multiplier_per_level);
minek ez a sok super?

2021-04-16 12:30 UTC, hegyhati commented on Player.java
> +            this.lvl=this.lvl+1;
++? :-)

2021-04-16 12:30 UTC, hegyhati commented on Unit.java
> +    }
no ezeket publicba kitenni nem kellene.

2021-04-18 16:13 UTC, nemetha17 commented
@hegyhati javítottam a hibákat.

2021-04-18 22:09 UTC, hegyhati requested changes

2021-04-18 22:09 UTC, hegyhati commented on Player.java
> +        this.xp = this.xp+this.getDMG();
Annyi van, hogy ha 5 elete van, en 10-et tudnek sebezni, akkor is csak 5 sebzest viszek be.

2021-04-18 22:09 UTC, hegyhati commented on Player.java
> +        }
Ez a logika a Unit-ban nincs mar meg? gyanusan kod duplikalas

2021-04-18 22:09 UTC, hegyhati commented on Player.java
> +            this.xp=this.xp-this.xp_per_level;
-=

2021-04-18 22:09 UTC, hegyhati commented on Player.java
> +            setAs(getAs()*cooldown_multiplier_per_level);
ezeket miert nem ered el siman es akkor csak += ?

2021-04-18 22:09 UTC, hegyhati commented on Unit.java
>      }
ne legyen ilyen public fuggveny. Ezt korabban hagyam bemenni?!

2021-04-19 10:15 UTC, nemetha17 commented
@hegyhati  kijavítottam a hibákat.

2021-04-22 16:59 UTC, hegyhati submitted a review, later dismissed
Reszemrol mar bemehet, bar a masodik komment mukodest erint, de talan masik csapatnal is bement igy, szoval nem curcial. Az elso meg csak "clean code"

2021-04-22 16:59 UTC, hegyhati commented on Player.java
> +            this.lvlup();
rendben van, de a dmg < > hp logika most ugyanugy megjelenik itt, mint a Unit.attack-ban. Egy szebb megoldas lenne, ha az a fv visszaterne a bevitt sebzes ertekevel, itt meg csak annyi lenne, hogy `this.xp+=super.attack(enemy)` Es akkor az, hogy meg kell kulonboztetni ket esetet, az csak egy helyen van lekezelve.

2021-04-22 16:59 UTC, hegyhati commented on Player.java
> +            this.hp+=this.hp_increase_per_level;
ezt a masik csapatnal lehet beneztem, de a feladatkiirasban amugy az volt, hogy ilyenkor ne csak megnojon az aktualis hp, hanem fel is menjen max-ra.

2021-04-22 17:00 UTC, hegyhati commented
viszont a tesztek amig elhasalnak, addig nem tudod bevinni.

2021-04-26 07:27 UTC, nemetha17 commented
@hegyhati Javítottam a hibákat bemehet akkor?

2021-04-26 13:44 UTC, hegyhati requested changes

2021-04-26 13:44 UTC, hegyhati commented on Player.java
> +            this.hp=this.maxHP+this.hp_increase_per_level;
en nem ertem, ezt a logikat miert ilyen nehez leprogramozni. Ha most ezt csinaljuk, akkor a hp-t felhuzza maxHP-ra, meg hozzaadja az increase-t. De a jobboldal ugyenannyi lesz az elso meg a masodiuk, meg a 25. szintlepes utan is.

2021-04-26 13:44 UTC, hegyhati commented on Player.java
> +            this.hp=this.maxHP+this.hp_increase_per_level;
Lehet a mukodest nem erted.
Kezdetben monjduk 10 max HP, az increase mondjuk 2. 
Csatazgatunk, ez lemegy 5-re. Szintet lepunk, akkor 12 lesz a maxHP meg az aktualis HP is. csatazgatunk, lemegy 1-re. Szintet lepunk, akkor 14 lesz a maxHP meg az aktualis HP is.

2021-04-26 13:44 UTC, hegyhati commented on Player.java
> +            this.hp=this.maxHP+this.hp_increase_per_level;
A te valtozatodban a maxHP marad mindig 10, es mindig 12-re allitodik be az aktualis hp szintlepeskor.

2021-04-27 08:01 UTC, nemetha17 commented
@hegyhati elvileg sikerült kijavítanom a HP-t szintlépéskor.

2021-04-27 15:03 UTC, hegyhati approved these changes, later dismissed
Mehet be

2021-05-03 10:43 UTC, phollaki approved these changes

2021-05-03 10:43 UTC, merged